minimumReleaseAge: 1440
minimumReleaseAgeStrict: true

packages:
  - examples/*
  - packages/*
  - testcases/*
  - website
allowBuilds:
  '@swc/core': true
  esbuild: true
  fsevents: true
  sharp: true
  unrs-resolver: true
