ignores:
  - '@jest/expect' # `expect` augmentation
  - '@size-limit/*'
  - '@types/node'
  - jest
  - jest-*
  - rimraf # depcheck issue
  - tslib
  - type-plus
  # testing augmentation (skipped right now)
  - strip-ansi
  # `withChalk` test (skipped right now)
  - chalk
