ignores:
  - '@jest/expect' # `expect` augmentation
  - '@size-limit/*'
  - '@types/node'
  - cross-env # depcheck issue: not detected since the v10 ESM rewrite
  - eslint-plugin-harmony
  - jest
  - jest-*
  - rimraf # depcheck issue
  - tslib
  - type-plus
  # testing augmentation (skipped right now)
  - strip-ansi
  # `withChalk` test (skipped right now)
  - chalk
